/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


declare global {
  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;
  }
}



import {
  MyProgressBar as MyProgressBar
} from './components/my-progress-bar/my-progress-bar';

declare global {
  interface HTMLMyProgressBarElement extends MyProgressBar, HTMLStencilElement {
  }
  var HTMLMyProgressBarElement: {
    prototype: HTMLMyProgressBarElement;
    new (): HTMLMyProgressBarElement;
  };
  interface HTMLElementTagNameMap {
    "my-progress-bar": HTMLMyProgressBarElement;
  }
  interface ElementTagNameMap {
    "my-progress-bar": HTMLMyProgressBarElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "my-progress-bar": JSXElements.MyProgressBarAttributes;
    }
  }
  namespace JSXElements {
    export interface MyProgressBarAttributes extends HTMLAttributes {
      max?: number;
      showValue?: boolean;
      value?: number;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
